version: "3.11"
services:
  db:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"

  bot:
    build: .
    env_file:
      - ./.env
    depends_on:
      - db
volumes:
  db-data:
